version: '3.6'

services:
  my-mongodb:
    image: mongo:4.4.4-bionic
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=go-store
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongodb/entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
#      - ./mongodb/data/configdb:/data/configdb
    networks:
      - go-store

  redis:
    image: 'docker.io/bitnami/redis:6.2-debian-10'
    container_name: redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    networks:
      - go-store

volumes:
  mongodb:

networks:
  go-store:
    driver: bridge